baseURL = "https://automationtesting.ar/"
languageCode = "en-us"
title = """Automation
&
Performance
testing"""
theme = "ananke"
resourceDir = "../resources"

MetaDataFormat         = "yaml" # Formato cabeceras
DefaultContentLanguage = "es"   # Idioma por defecto del contenido
SectionPagesMenu       = "main" #
Paginate               = 15      # Posts por página en main
googleAnalytics        = ""     # Código para estadísticas web
enableRobotsTXT        = true   # Buscadores

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params.contact]
    email = 'imende.mariano@gmail.com'
    phone = '+54-1162271394'


[params]
  favicon="static/favicon.ico"
  toc= true
  customCSS = ["https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"]
  custom_css = ["css/custom.css"]
  max_content_width = "90%"  # Ajusta el ancho máximo del contenido
  show_reading_time = true
  commentoEnable = true
  recent_posts_number = 10
  site_logo = ""
  email = "imende.mariano@gmail.com"
  #twitter = "https://twitter.com/GoHugoIO"
  instagram = "https://www.instagram.com/mariano_imende/?igsh=ZnU0YTJrNTYxcTM3"
  youtube = "https://www.youtube.com/results?search_query=performance+and+automation+testing"
  github = "https://github.com/MarianoImende"
  linkedin = "https://www.linkedin.com/in/mariano-imende"
  read_more_copy= "Leer más sobre este artículo"
  text_color = "black"
  author = "Mariano Imende"
  description = "Blog personal sobre testing de software, automatización de pruebas y performance testing"
  dateFormat = "Mon, Jan 2, 2006"
  themeColor = "black"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  featured_image  = "/images/portada.jpg"

[services.disqus]
  shortname = 'Mariano Imende'

[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Artículos y Tutoriales"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "Contacto"
    url = "/contact/"
    weight = 3
